# GitHub Pages Jekyll 配置
# 禁用Jekyll处理，使用纯静态文件

plugins: []
markdown: kramdown
highlighter: rouge

# 排除不需要的文件
exclude:
  - README.md
  - Dockerfile
  - docker-compose.yml
  - nginx.conf
  - .dockerignore
  - .gitignore
  - deploy.sh
  - server.sh
  - logs/
  - .qoder/
  - GITHUB_PAGES_SETUP.md
  - status.html
  - check-pages.sh

# 包含的文件
include:
  - .htaccess

# 基本设置
title: "LineWeaver - 文本换行符去除工具"
description: "一个简单优雅的文本换行符去除工具，让文本像流水般顺畅连续"
url: "https://misonl.github.io"
baseurl: "/LineWeaver"

# 构建设置
safe: true
incremental: false
lsi: false